version: 2.1

executors:
  gradle-executor:
    docker:
      - image: circleci/openjdk:11-jdk

jobs:
  publish-plugin:
    executor: gradle-executor
    steps:
      - checkout
      - run:
          name: Publish Plugin.
          command: |
            gradle bintrayUpload

workflows:
  version: 2
  deploy:
    jobs:
      - publish-plugin:
          filters:
            branches:
              only:
                - main
